name: Trigger Rust Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  run-rust-tests:
    name: Run Rust Tests in Submodule
    uses: BlakeDonn/trustystack-rust/.github/workflows/rust-tests.yml@main  # Reuse the workflow

