name: Trigger Rust Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  trigger-rust-tests:
    name: Trigger Rust Tests in Submodule
    runs-on: ubuntu-latest

    steps:
    - name: Call Rust Submodule Workflow Dispatch
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/BlakeDonn/trustystack-rust/actions/workflows/rust-tests.yml/dispatches \
          -d '{"ref":"main"}'

